//Function that returns a license badge based on which license is passed in
// If there is no license, returns an empty string

function renderLicenseBadge(license){return `https://img.shields.io/badge/License:%20${license}-pink`};

function renderLicenseUrl(license){
  var licenseUrl;
  switch(license){
  case 'Apache':
    licenseUrl='https://www.apache.org/licenses/LICENSE-2.0';
    break;
  case 'Berkeley':
    licenseUrl='https://opensource.org/licenses/BSD-3-Clause';
    break;
  case 'GPL':
    licenseUrl='https://www.gnu.org/licenses/gpl-3.0.en.html';
    break;
  case 'MIT':
    licenseUrl='https://opensource.org/licenses/MIT';
    break;
  case 'Mozilla':
    licenseUrl='https://www.mozilla.org/en-US/MPL/';
    break;
  default:"None"
   return 'Cannot detect link!'
}
return `[${license}](${licenseUrl})`
}

function renderLicense(license) {
  return `![](${renderLicenseBadge(license)})
  ![](${renderLicenseUrl(license)})
  `
}
function generateMarkdown(data){return`
## ${data.title}

## Repository ##
${data.project}


## Table of Contents ##
* [Description](#Description-)
* [Installation](#Installation-)
* [Usage](#Usage-)
* [Tech](#Tech-)
* [Testing](#Testing-)
* [Contribution](#Contribution-)
* [Licensing](#Licensing-)
* [Contact](#Contact-)


## Description ##
${data.description}

## Installation ##
${data.install}

## Usage ##
${data.usage}

## Tech ##
${data.tech}

## Testing ##
${data.test}

## Contribution ##
${data.contribution}

## Licensing ##
NOTICE: This application is issued and used under provisions established by ${renderLicense(data.license)}

## Contact ##
For any questions about this project, contact me at:
- Github: ${data.username};
- Email: ${data.email};\n
This README was generated by ${data.name}.`;}

module.exports = generateMarkdown;

